version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    ports:
      - 1433:1433
    volumes:
      - ./sql/data:/var/opt/mssql/data
      - ./sql/logs:/var/opt/mssql/log
      - ./sql/secrets:/var/opt/mssql/secrets

    